export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const SET_SELECTED_MOVIE_ID = 'SET_SELECTED_MOVIE_ID';
export const SET_FILTER = 'SET_FILTER';
export const SET_SORT_OPTION = 'SET_SORT_OPTION';
